config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tasks do
    member do
      patch 'complete'
    end
  end
  resources :schedules
  resources :articles
  resources :orgs
  resources :users
  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               sign_up: 'register',
               edit: 'settings'
             }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: redirect('/tasks')
  end
  root to: 'application#home'

  get '/home', to: 'application#home', as: 'home'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'
  get '/unauthorized', to: 'application#unauthorized', as: 'unauthorized'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  # config/routes.rb
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user
  belongs_to :schedule

  scope :complete, -> { where('tasks.completed_date IS NOT NULL') }
  scope :incomplete, -> { where('tasks.completed_date IS NULL') }
  scope :past_due, -> { where('tasks.due_date < ?', Time.now) }

  def completion
    return if completed_date.nil?

    due_date = Time.now + schedule.duration.days
    Task.create(
      name: schedule.name,
      due_date: due_date,
      schedule_id: schedule.id,
      user_id: schedule.user_id
    )
  end
end

# == Schema Information
#
# Table name: tasks
#
#  id             :integer          not null, primary key
#  completed_date :datetime
#  description    :text
#  due_date       :datetime
#  name           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  schedule_id    :integer
#  user_id        :integer
#

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_authorize_task, only: %i[show edit update destroy complete]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = policy_scope(Task)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new(task_params)
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.org_id = current_user.org_id

    respond_to do |format|
      if @task.save
        format.html do
          redirect_to @task, notice: 'Task was successfully created.'
        end
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html do
          redirect_to tasks_url, notice: 'Task was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html do
        redirect_to tasks_url, notice: 'Task was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def complete
    @task.completed_date = (Time.now if @task.completed_date.nil?)
    respond_to do |format|
      if @task.save
        @task.completion
        format.html do
          redirect_to tasks_url
        end
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_authorize_task
    @task = Task.find(params[:id])
    authorize(@task)
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def task_params
    params.require(:task).permit(:name, :description, :org_id, :article_id, :due_date)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.slim
.panel.panel-default
  .panel-body
    = form_for @task do |f|
      - if @task.errors.any?
        #error_explanation
          h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
          ul
            - @task.errors.full_messages.each do |message|
              li = message

      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control input-sm'
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control input-sm'
      .form-group
        = f.label :due_date
        = f.date_select :due_date, class: 'form-control input-sm'
        = f.hidden_field :schedule_id
      = f.submit 'Save', class: 'btn btn-primary btn-sm btn-block'

app/views/tasks/edit.html.slim
h3
  = link_to 'Back', tasks_path, class: 'btn btn-default btn-sm pull-left'
  span &nbsp Editing Task

== render 'form'

app/views/tasks/index.html.slim
h3
  span &nbsp Incomplete Tasks

table.table.table-striped.table-sm
  thead
    tr
      th
      th Name
      th Asset
      th Due
      th Completed
      th

  tbody
    - @tasks.incomplete.order('due_date ASC').each do |task|
      tr
        td
          - if task.completed_date.nil?
            = link_to '<input type="checkbox">'.html_safe, complete_task_path(task), :method => :patch
          - else
            = link_to '<input type="checkbox" checked>'.html_safe, complete_task_path(task), :method => :patch
        td = task.name
        td = task.schedule.article.name
        td
          - if task.due_date < Time.now
            .text-danger
              = task.due_date&.strftime("%b %d, %y")
          - else
            = task.due_date&.strftime("%b %d, %y")
        td = task.completed_date&.strftime("%b %d, %y")
        td
          = link_to task_path(task)
            i.fa.fa-space.fa-eye
          = link_to edit_task_path(task)
            i.fa.fa-space.fa-pencil
          = link_to task, data: { confirm: 'Are you sure?' }, method: :delete
            i.fa.fa-space.fa-trash

h3
  span &nbsp Completed Tasks

table.table.table-striped.table-sm
  thead
    tr
      th
      th Name
      th Asset
      th Due
      th Completed
      th

  tbody
    - @tasks.complete.each do |task|
      tr
        td
          - if task.completed_date.nil?
            = link_to '<input type="checkbox">'.html_safe, complete_task_path(task), :method => :patch
          - else
            = link_to '<input type="checkbox" checked>'.html_safe, complete_task_path(task), :method => :patch
        td = task.name
        td = task.schedule.article.name
        td = task.due_date&.strftime("%b %d, %y")
        td = task.completed_date&.strftime("%b %d, %y")
        td
          = link_to task_path(task)
            i.fa.fa-space.fa-eye
          = link_to edit_task_path(task)
            i.fa.fa-space.fa-pencil
          = link_to task, data: { confirm: 'Are you sure?' }, method: :delete
            i.fa.fa-space.fa-trash

app/views/tasks/new.html.slim
h1 New task

== render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.slim
h3
  = link_to 'Back', tasks_path, class: 'btn btn-default btn-sm pull-left'
  span &nbsp
  = @task.name
  = link_to 'Edit', edit_task_path(@task), class: 'btn btn-primary btn-sm pull-right'
.panel.panel-default
  .panel-body
    p
      strong Name: &nbsp
      = @task.name
    p
      strong Description: &nbsp
      = @task.description
    p
      strong Due Date: &nbsp
      = @task.due_date&.strftime("%b %d, %y")
    p
      strong Completed Date: &nbsp
      = @task.completed_date&.strftime("%b %d, %y")