config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tasks do
    member do
      patch 'complete'
    end
  end
  resources :schedules
  resources :articles
  resources :orgs
  resources :users
  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               sign_up: 'register',
               edit: 'settings'
             }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: redirect('/tasks')
  end
  root to: 'application#home'

  get '/home', to: 'application#home', as: 'home'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'
  get '/unauthorized', to: 'application#unauthorized', as: 'unauthorized'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  # config/routes.rb
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :org
  has_many :schedules
end

# == Schema Information
#
# Table name: articles
#
#  id               :integer          not null, primary key
#  department       :string
#  description      :string
#  location         :string
#  manufacturer     :string
#  model_number     :string
#  name             :string
#  purchase_invoice :string
#  purchase_price   :decimal(11, 4)   default(0.0)
#  purchase_vendor  :string
#  replacement_cost :decimal(11, 4)   default(0.0)
#  room             :string
#  serial_number    :string
#  useful_life_span :decimal(11, 4)   default(0.0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  org_id           :integer
#

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_authorize_article, only: %i[show edit update destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = policy_scope(Article)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.org_id = current_user.org_id

    respond_to do |format|
      if @article.save
        format.html do
          redirect_to @article, notice: 'Article was successfully created.'
        end
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json do
          render json: @article.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html do
          redirect_to @article, notice: 'Article was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json do
          render json: @article.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html do
        redirect_to articles_url, notice: 'Article was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_authorize_article
    @article = Article.find(params[:id])
    @schedules = @article.schedules
    authorize(@article)
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def article_params
    params.require(:article).permit(
      :name, :department, :location, :manufacturer, :model_number, :room,
      :serial_number, :useful_life_span, :description, :org_id,
      :replacement_cost, :purchase_price, :purchase_invoice, :purchase_vendor
    )
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.slim
.panel.panel-default
  .panel-body
    = form_for @article do |f|
      - if @article.errors.any?
        #error_explanation
          h2 = "#{pluralize(@article.errors.count, "error")} prohibited this asset from being saved:"
          ul
            - @article.errors.full_messages.each do |message|
              li = message

      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control input-sm'
      .form-group
        = f.label :location
        = f.text_field :location, class: 'form-control input-sm'
      .form-group
        = f.label :room
        = f.text_field :room, class: 'form-control input-sm'
      .form-group
        = f.label :department
        = f.text_field :department, class: 'form-control input-sm'
      .form-group
        = f.label :manufacturer
        = f.text_field :manufacturer, class: 'form-control input-sm'
      .form-group
        = f.label :model_number
        = f.text_field :model_number, class: 'form-control input-sm'
      .form-group
        = f.label :serial_number
        = f.text_field :serial_number, class: 'form-control input-sm'
      .form-group
        = f.label :replacement_cost
        = f.number_field :replacement_cost, class: 'form-control input-sm'
      .form-group
        = f.label :purchase_vendor
        = f.text_field :purchase_vendor, class: 'form-control input-sm'
      .form-group
        = f.label :purchase_invoice
        = f.text_field :purchase_invoice, class: 'form-control input-sm'
      .form-group
        = f.label :purchase_price
        = f.number_field :purchase_price, class: 'form-control input-sm'
      .form-group
        = f.label :notes
        = f.text_area :description, class: 'form-control input-sm'
      = f.submit 'Save', class: 'btn btn-primary btn-sm btn-block'

app/views/articles/edit.html.slim
h3
  = link_to 'Back', articles_path, class: 'btn btn-default btn-sm pull-left'
  span &nbsp Editing Asset

== render 'form'

app/views/articles/index.html.slim
h3
  = link_to 'New', new_article_path, class: 'btn btn-success btn-sm pull-right'
  span &nbsp Assets

table.table.table-striped.table-sm
  thead
    tr
      th Name
      th Location
      th Room
      th

  tbody
    - @articles.each do |article|
      tr
        td = article.name
        td = article.location
        td = article.room
        td
          = link_to article
            i.fa.fa-space.fa-eye
          = link_to article, data: { confirm: 'Are you sure?' }, method: :delete
            i.fa.fa-trash

app/views/articles/new.html.slim
h3
  = link_to 'Back', articles_path, class: 'btn btn-default btn-sm pull-left'
  span &nbsp New Asset

== render 'form'

app/views/articles/show.html.slim
h3
  = link_to 'Back', articles_path, class: 'btn btn-default btn-sm pull-left'
  span &nbsp
  = @article.name
  = link_to 'Edit', edit_article_path(@article), class: 'btn btn-primary btn-sm pull-right'
.panel.panel-default
  .panel-body
    p
    strong Name: &nbsp
    = @article.name
    p
    strong Location: &nbsp
    = @article.location
    p
    strong Room: &nbsp
    = @article.room
    p
    strong Maintenance Schedule: &nbsp
    = link_to 'New', new_schedule_path({schedule: {article_id: @article.id, user_id: current_user.id}}), class: 'btn btn-success btn-sm pull-right'
    p
      == render partial: 'schedules/schedules', locals: { schedules: @article.schedules }
    p
    strong Department: &nbsp
    = @article.department
    p
    strong Manufacturer: &nbsp
    = @article.manufacturer
    p
    strong Model Number: &nbsp
    = @article.model_number
    p
    strong Serial Number: &nbsp
    = @article.serial_number
    p
    strong Replacement Cost: &nbsp $
    = @article.replacement_cost
    p
    strong Purchase Vendor: &nbsp
    = @article.purchase_vendor
    p
    strong Purchase Invoice: &nbsp
    = @article.purchase_invoice
    p
    strong Purchase Price: &nbsp $
    = @article.purchase_price
    p
    strong Notes: &nbsp
    = @article.description