config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tasks do
    member do
      patch 'complete'
    end
  end
  resources :schedules
  resources :articles
  resources :orgs
  resources :users
  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               sign_up: 'register',
               edit: 'settings'
             }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: redirect('/tasks')
  end
  root to: 'application#home'

  get '/home', to: 'application#home', as: 'home'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'
  get '/unauthorized', to: 'application#unauthorized', as: 'unauthorized'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  # config/routes.rb
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/org.rb
# frozen_string_literal: true

class Org < ApplicationRecord
  has_many :articles
  has_many :schedules, through: :articles
  has_many :users
end

# == Schema Information
#
# Table name: orgs
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/orgs_controller.rb
# frozen_string_literal: true

class OrgsController < ApplicationController
  before_action :set_authorize_org, only: %i[show edit update destroy]

  # GET /orgs
  # GET /orgs.json
  def index
    @orgs = policy_scope(Org)
  end

  # GET /orgs/1
  # GET /orgs/1.json
  def show; end

  # GET /orgs/1/edit
  def edit; end

  # PATCH/PUT /orgs/1
  # PATCH/PUT /orgs/1.json
  def update
    respond_to do |format|
      if @org.update(org_params)
        format.html do
          redirect_to @org, notice: 'Org was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @org }
      else
        format.html { render :edit }
        format.json { render json: @org.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_authorize_org
    @org = Org.find(params[:id])
    authorize(@org)
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def org_params
    params.require(:org).permit(:name)
  end
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/views/orgs/_form.html.slim
.panel.panel-default
  .panel-body
    = form_for @org do |f|
      - if @org.errors.any?
        #error_explanation
          h2 = "#{pluralize(@org.errors.count, "error")} prohibited this org from being saved:"
          ul
            - @org.errors.full_messages.each do |message|
              li = message

      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control input-sm'
      = f.submit 'Save' , class: 'btn btn-primary btn-sm btn-block'

app/views/orgs/edit.html.slim
== render 'layouts/settings_navigation'

h3
  = link_to 'Back', org_path(@org), class: 'btn btn-default btn-sm pull-left'
  span &nbsp
  = @org.name
== render 'form'

app/views/orgs/index.html.slim
h1 Listing orgs

table class="table"
  thead
    tr
      th Name
      th
      th

  tbody
    - @orgs.each do |org|
      tr
        td = org.name
        td = link_to 'Show', org
        td = link_to 'Edit', edit_org_path(org)

br

app/views/orgs/new.html.slim
h1 New org

== render 'form'

= link_to 'Back', orgs_path

app/views/orgs/show.html.slim
== render 'layouts/settings_navigation'

h3
  span &nbsp
  = @org.name
  = link_to 'Edit', edit_org_path(@org), class: 'btn btn-primary btn-sm pull-right'
.panel.panel-default
  .panel-body
    p
      strong Name: &nbsp
      = @org.name