config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tasks do
    member do
      patch 'complete'
    end
  end
  resources :schedules
  resources :articles
  resources :orgs
  resources :users
  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               sign_up: 'register',
               edit: 'settings'
             }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: redirect('/tasks')
  end
  root to: 'application#home'

  get '/home', to: 'application#home', as: 'home'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'
  get '/unauthorized', to: 'application#unauthorized', as: 'unauthorized'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  # config/routes.rb
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/_navigation.html.slim
ul class="nav navbar-nav"
  - if current_user
    li= link_to('<span class="fa fa-lg fa-tachometer"></span> Dashboard'.html_safe, tasks_path)
    li= link_to('<span class="fa fa-lg fa-tasks"></span> Assets'.html_safe, articles_path)
  - else
    li= link_to('<span class="fa fa-lg fa-phone"></span> Contact'.html_safe, contact_path)
    li= link_to('<span class="fa fa-lg fa-user"></span> About'.html_safe, about_path)

ul class="nav navbar-nav navbar-right"
  - if current_user
    li= link_to('<span class="fa fa-lg fa-cog"></span> Settings'.html_safe, edit_user_registration_path)
    li= link_to('<span class="fa fa-lg fa-power-off"></span> Log out'.html_safe, destroy_user_session_path, method: 'delete')
  - else
    li= link_to('<span class="fa fa-lg fa-sign-in"></span> Login'.html_safe, new_user_session_path)
    li= link_to('<span class="fa fa-lg fa-download"></span> Register'.html_safe, new_user_registration_path)

app/views/layouts/_notifications.html.slim
- if notice
  .alert.alert-info
    p= notice

- if alert
  .alert.alert-warning
    p= alert

app/views/layouts/_settings_navigation.html.slim
.navbar.navbar-default
  .container-fluid
    ul class="nav navbar-nav"
      li= link_to('<span class="fa fa-lg fa-user"></span> Profile'.html_safe, edit_user_registration_path)
      li= link_to('<span class="fa fa-lg fa-building"></span> Org'.html_safe, org_path(current_user.org))
      li= link_to('<span class="fa fa-lg fa-users"></span> Users'.html_safe, users_path)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title><%= content_for?(:title) ? yield(:title) + " - #{APPLICATION_NAME}" : "#{APPLICATION_NAME}" %></title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	  <%= csrf_meta_tags %>

  </head>

  <body>
	  <nav class="navbar navbar-default">
		  <div class="container-fluid">
			  <div class="navbar-header">
				  <button type="button" class="navbar-toggle collapsed"
				          data-toggle="collapse" data-target="#menu-collapse">
					  <span class="sr-only">Toggle navigation</span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
				  </button>
				  <%= link_to APPLICATION_NAME, root_path, class: 'navbar-brand' %>
			  </div>

			  <div class="collapse navbar-collapse" id="menu-collapse">

				  <%= render 'layouts/navigation' %>

			  </div>
		  </div>
	  </nav>

	  <div class="container">

		  <%= render 'layouts/notifications' %>

      <div class="row">
        <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 col-xs-12">

          <%= yield %>

        </div>
      </div>
	  </div>
  </body>
</html>